### ISSUE TITLE
BODY_XPATH does not support substring or other string functions

### ISSUE THREAD

**Issue by amduser** [castlemock/castlemock#220] opened 2020-05-20 21:32 UTC
**Describe the bug**
BODY_XPATH is unable to parse expressions that return strings like substring.  Instead an exception is thrown that "Can not convert #STRING to a NodeList!"

**To Reproduce**
In a mock SOAP response, this will return an empty value for the node 
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://example.com/ws/schemas/1.0">
   <soapenv:Header/>
   <soapenv:Body>
      <web:Response>${BODY_XPATH(expression="substring(//input/example/text(), 0, 3)")}</web:Response>
   </soapenv:Body>
</soapenv:Envelope>

**Expected behavior**
This should instead return the request substring of //input/example/text()

**Comment by karldahlgren** [comment] 2020-05-24 19:57
The bug fix has now been released with the latest version of Castle Mock, v1.49.

Thank you once again for all your help.
Best regards,
Karl Dahlgren

**Closed by karldahlgren** 2020-05-24 19:57 UTC
Labels: bug

**Comment by stefan93** [comment] 2020-06-29 11:25
Hi,

I have tried to use string function in expression:

${BODY_XPATH(expression="substring-after(//CheckPRNStatus/strPRN/text(), "V")")}

I got error: mismatched input 'V' expecting {',', ')'}.
It looks like literal string can't be passed as argument to xpath functions?
I am not sure if this is related to this bug, or I am using it wrong. I can open detailed separate issue, if needed.

**Comment by karldahlgren** [comment] 2020-06-29 21:00
Hi @stefan93.
Would it be possible for you to try the following expression?
    ${BODY_XPATH(expression="substring-after(//CheckPRNStatus/strPRN/text(), \"V\")")}

My guess is that you have to escape the quotation marks.
Thanks!
Best regards,
Karl Dahlgren

**Comment by stefan93** [comment] 2020-06-30 15:20
Hi @karldahlgren,

I tried escaping quotes around "V". But same results.

-  ${BODY_XPATH(expression="substring-after(//CheckPRNStatus/strPRN/text(), \\"V\\")")} and
${BODY_XPATH(expression="substring-after(//CheckPRNStatus/strPRN/text(), /"V/")")}
line 1:75 mismatched input 'V' expecting {',', ')'}
ERROR: com.castlemock.core.basis.utility.XPathUtility - Unable to evaluate xpath expression
javax.xml.transform.TransformerException: Expected ,, but found:

-  ${BODY_XPATH(expression="substring-after(//CheckPRNStatus/strPRN/text(), \\\\"V\\\\")")}
line 1:76 mismatched input 'V' expecting {',', ')'}
ERROR: com.castlemock.core.basis.utility.XPathUtility - Unable to evaluate xpath expression
javax.xml.transform.TransformerException: Expected ), but found:


Thank you for your time.

**Comment by karldahlgren** [comment] 2020-07-01 21:10
Hi @stefan93.
Good news! I was able to reproduce the issue and I believe that I have located where the problem could be. Unfortunately, the fix requires code changes. I will try to fix the issue before the end of this week. I can prepare a release as soon as the issue has been resolved.

My apologies for the inconveniences.
I will keep you updated. Thank you for reporting this.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment] 2020-07-02 20:29
Hi @stefan93.
The issue has been resolved and be part of the next release. I will prepare a new release at the end of this week.
You expression will now work if you write it like this:
   
    substring-after(//CheckPRNStatus/strPRN/text(), 'V\')

I unable to get it to work with double quotation marks, so you can instead use single quotation marks instead.
