### ISSUE TITLE
XPath expression deletting

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#84] opened 2018-10-11 07:48 UTC
Hello,

the bug https://github.com/castlemock/castlemock/issues/76 is not really fixed with version 1.30. Now you cannot delete at all the first defined X-Path Expression.

I wonder, did someone test the fixes at all?

Regards,
Milko

**Comment by karldahlgren** [comment] 2018-10-14 16:09
Hi @milkotodorov.
The issue has now been resolved and will be part of the next release. Planning on releasing a new release later tonight.

However, I want to remark on the following comment:
> I wonder, did someone test the fixes at all?

This kind of comments are looked down upon in this project and not welcome here. All the contributors work on a voluntary basis and doing so to make the project better. We are all trying to do something good here and have fun while we doing it :)

Now, that being said, thank you for reporting this issue.
Best regards,
Karl Dahlgren

**Comment by milkotodorov** [comment] 2018-10-14 18:15
Hi @karldahlgren,

I've just compiled and tested the master branch, but unfortunately the last one X-Path Expression left in the list cannot be deleted. Do I need to open another issue? Or this here is enough?

Regards,
Milko

**Comment by karldahlgren** [comment] 2018-10-14 18:18
Hi @milkotodorov.
Thank you for testing.
Are you sure that the browser hasn't cached any resources such as javascript files?
Not able to reproduce it at the moment.

(And yes, the ticket here is enough :) )

Best regards,
Karl Dahlgren

**Comment by milkotodorov** [comment] 2018-11-29 13:20
Hi @karldahlgren,

with version 1.33 we cannot delete any XPath defined anymore.
I think it is not an browser cache problem.

**Comment by keroberos99** [comment] 2018-12-25 09:01
> Hi @karldahlgren,
> 
> with version 1.33 we cannot delete any XPath defined anymore.
> I think it is not an browser cache problem.

I found same problem, 
it come from script onclick for delete that generated when create new xpath with single-quote contained. (ex **//path/detail/field[text()='expected']** )
after fix that code in  "xpathTable.js", the new xpath with single-quote can remove properly.

**Comment by karldahlgren** [comment] 2018-12-26 22:09
Hi @keroberos99.
Thank you so much for finding this. I will fix this as soon as I can. It will be part of the next release.

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment] 2019-01-03 20:42
Hi everyone.
This issue has now been resolved and will be part of next release.
Sorry for talking such a long time.

Best regards,
Karl Dahlgren

**Closed by karldahlgren** 2019-01-03 20:42 UTC
Labels: bug
