### ISSUE TITLE
Large file imported project issue.

### ISSUE THREAD

**Issue by nikhilniki987** [castlemock/castlemock#599] opened 2023-03-02 14:00 UTC
**Describe the bug**
We are not able to import the project XML file (9MB) which we exported from the castle mock, when we import the XML file in the castle mock we are getting "Request Entity To Large Error", and we changed the file size in application properties to 50MB but still, we are not able to import.

**To Reproduce**
1. Go to the castle mock 
2. Exported the XML project file which is more than 10MB
3. Delete the project in the castle mock
4. Try to import the exported XML file
5. Observe the error attached screenshot 

**Expected behavior**
The project should be imported 

**Screenshots**
![image](https://user-images.githubusercontent.com/126774282/222448365-cf7e6c10-2897-4685-9721-d6de7a037699.png)
![image](https://user-images.githubusercontent.com/126774282/222448394-fab9a768-5a3b-4656-9d8f-b6a523a5ecc6.png)

**Desktop (please complete the following information):**
 - OS: [Windows (Client browser) Linux (Server) ]
 - Browser [Chrome]
 - Version [110.0.5481.178]

**Additional context:**
NA

**WSDL files or other resource attachments:** 
NA

**Comment by karldahlgren** [comment] 2023-03-02 14:49
I appreciate you using the template, but this is still a duplicate of issue #598, which was a duplicate of #597. **Do not open issues for issues that already exists!** If you have more information to provide regarding the issue, please add that to the already existing issue.

**Closed by karldahlgren** 2023-03-02 14:49 UTC
