### ISSUE TITLE
Only Request body is varying across api's

### ISSUE THREAD

**Issue by jeevitesh** [castlemock/castlemock#583] opened 2023-01-11 09:59 UTC
Hello,
I need to mock external api’s in which across api url remain same, but only request body varies like mentioned below

External Api 1
URL
/api/gatewayservice
`Request body
<Customer> <Request> XXX..XXX </Request> </Customer>`

External Api 2
URL
/api/gatewayservice

Request body
`<GetPriceAndAvail> <Request> XXXXX </Request> </GetPriceAndAvail>`

as only request body is varying across api's in this case how to handle in Castle mock ?

I thought of adding if statement in the XPATH, but how to send different response for different type of request payload.

Please share the approach how it can be handled.

Thank you in advance.

**Comment by karldahlgren** [comment] 2023-01-11 19:52
Closing this since it is a duplicate of issue 583. Please don't open multiple issues for same question or problem.

**Closed by karldahlgren** 2023-01-11 19:52 UTC

**Comment by jeevitesh** [comment] 2023-01-12 09:18
hi, nobody is replying to the question .. we adopted castlemock framework and there is no community support for our blockers
