### ISSUE TITLE
Getting Error consuming SOAP service from C# generate client

### ISSUE THREAD

**Issue by arthurvaverko** [castlemock/castlemock#87] opened 2018-11-01 07:06 UTC
I am using the following  2 WSDL: https://gist.github.com/arthurvaverko/7ebb850ff9c2903509a0158005741e41

Importing it to castelmock and generating a client proxy using same file.

getting the following error from both:

> System.ServiceModel.ProtocolException: 'The content type application/xml of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 157 bytes of the response were: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error-response><error-message>Unable to identify SOAP operation: TST</error-message></error-response>'.'

U have sniffed the outbound request made by the generated c# client and it seems fine to me ..
it also works with getSandbox.com

```
POST /mock/soap/project/CUgZt8/TST HTTP/1.1
accept-encoding: gzip, deflate
content-length: 380
content-type: text/xml; charset=utf-8
expect: 100-continue
host: 172.31.242.99:8080
proxy-connection: Keep-Alive
soapaction: "GetBasePackageList"
Cache-Control: no-cache

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetBasePackageListRequestElement xmlns="urn:atc:kz:stst:fmc.api.schema"><login xmlns="">Testing_Console</login><systemType xmlns="">Test</systemType></GetBasePackageListRequestElement></s:Body></s:Envelope>


```

**Comment by arthurvaverko** [comment] 2018-11-04 09:52
Another related issue, i have the second test2.wsdl file without soapAction attributes meaning it will have to match by operation name, but castle mock is not able to match any request made from the c# client.

example operation is:

```
<operation name="GetFttbInfo">
      <input name="GetFttbInfoInput" message="tns:GetFttbInfoRequest" />
      <output name="GetFttbInfoOutput" message="tns:GetFttbInfoResponse" />
</operation>
```

**Comment by karldahlgren** [comment] 2018-11-04 21:07
Hi @arthurvaverko.
Thank you for reporting this issue. It seems that the wrong Content-Type was used. I have resolved this issue and it will be part of the next release.
I have also re-written the whole parsing of WSDL files. If the Content-Type fix doesn't resolve your issue, then I would recommend you to try to re-import the WSDL again.

Thank you very much once again. Please feel free to contact me again if you are having any other issues.

Best regards,
Karl Dahlgren

**Closed by karldahlgren** 2018-11-04 21:07 UTC
Labels: bug

**Comment by arthurvaverko** [comment] 2018-11-05 10:29
thanks .. how can i get the new release and \ or compile from source ? 
do you have any instructions on how to compile it ? i have tried to use vsCode but had trouble finding the lexer and parser clasess .. something to do with them no inside the .classpath i believe ..

**Comment by karldahlgren** [comment] 2018-11-06 22:00
Hi @arthurvaverko.
I believe I might know what the problem is here. It seems that the namespace extracted from the body isn't done correctly when it is included in the actual element. I can fix this. In the meantime, you can always turn off the match of namespace by changing the identify strategy in the SOAP operation setting page from "element and namespace" to just "element". That should resolve your issue.

I will get started on fixing this.
My apologies for the inconvenience. 

Best regards,
Karl Dahlgren

**Comment by arthurvaverko** [comment] 2018-11-07 09:04
yes that helped .. thanks ..
