### ISSUE TITLE
Unable to delete XPaths filters in SOAP operation

### ISSUE THREAD

**Issue by anaperaita** [castlemock/castlemock#113] opened 2019-02-06 16:04 UTC
**Describe the bug**
When I import a previously exported SOAP project and I try to delete any Xpath I can't

**To Reproduce**
1.  Create a SOAP Project 
2. Create one response that filters the requests using xpath
3. Export the project
4 Import the project (in another instance of castlemock)
5 Try to delete the previously created Xpath in the exported project

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome
 - Version: docker image castlemock/castlemock:1.34

There is this error in the console: 
Uncaught SyntaxError: missing ) after argument list

It is because the '  are not escaped in a case like this:
removeXpath('//Em[@R='abcdefg']')

**Comment by mhewedy** [comment] 2019-02-06 16:40
Why not just send a PR?

**Comment by karldahlgren** [comment] 2019-02-06 21:58
Hi @anaperaita.
Thank you for reporting this bug. I will take a look at it as soon as possible. Most likely sometime during this weekend :)

Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment] 2019-02-17 07:51
Hi @anaperaita.
Thank you once again for raising this issue. Unfortunately, I haven't been able to reproduce this issue. This was a bug that was resolved in 1.34. I'm wondering if your browser might have cached the old JS file. Would it be possible for you to try to do a hard refresh on the page and see if that helps?

Thank you.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment] 2019-03-03 13:16
Closing this since we were able to reproduce this on a later version. The issue should have been resolved.

Best regards,
Karl Dahlgren

**Closed by karldahlgren** 2019-03-03 13:16 UTC
Labels: bug
